### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "testuser"
}

### signup
POST http://localhost:3000/auth/signup/request-otp
Content-Type: application/json

{
  "email": "satviksharma3123@gmail.com"
}

### verify-otp
POST http://localhost:3000/auth/signup/verify
Content-Type: application/json

{
  "name" : "ss",
  "email" : "satviksharma3123@gmail.com",
  "password" : "lily@123",
  "role" : "retailer",
  "otp" : "415368"
}

### forgot-password
POST http://localhost:3000/auth/forgot-password/request-otp
Content-Type: application/json

{
  "email": "satviksharma3123@gmail.com"
}

### verify-forgot-password-otp
POST http://localhost:3000/auth/forgot-password/verify
Content-Type: application/json

{
  "email" : "satviksharma3123@gmail.com",
  "newPassword" : "lily@1234",
  "otp" : "480456"
}