### get all products(retail only for customers)
GET http://localhost:3000/customers/availableproducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzYXR2aWtzaGFybWEzMTIzQGdtYWlsLmNvbSIsIm5hbWUiOiJDb25vciBNY0dyZWdvciIsInJvbGUiOiJyZXRhaWxlciIsImlhdCI6MTc2MDY4MjU4NywiZXhwIjoxNzYwNjg2MTg3fQ.ZCK6tPEDTP-jdrgwLIoEAIYuP0irjnqivrn4vcy_10o

{

}